# -*- coding: utf-8 -*-
"""Open_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y61RpMQHY31ARp5u1XmIaIhrP3Sau-BC
"""

import requests

pN='1'
nOR='10'
startD='20191230'
endD='20210623'
url ='http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19InfStateJson?serviceKey=zTa2HPaDXF3mBGgFN1l0EkCP%2BOWRPIUmkAoGZeu8oQDco%2FUapbW7xPoDPCHaRGPP9A43rMTBBnljgtcas9rZxA%3D%3D&pageNo={}&numOfRows={}&startCreateDt={}&endCreateDt={}'.format(pN,nOR,startD,endD)

req=requests.get(url)
result=req.text

print(result)

from bs4 import BeautifulSoup

xmlsoup= BeautifulSoup(result,'lxml-xml')
print(xmlsoup)

xml_item=xmlsoup.findAll('item')
len(xml_item)

from tqdm import tqdm

com_re=list()

for t in tqdm(xml_item):
    date=t.find('stateDt').text
    count=t.find('decideCnt').text
    
    com_re.append([date,count])
    
com_re

