# -*- coding: utf-8 -*-
"""연령별 인구통계

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DyWXYGVLIPPb5TK2dplZJvy_K69S9YBB
"""

!dir *.csv

!cp *.csv /content/drive/MyDrive/

import pandas as pd
filename='2021_age.csv'
j=pd.read_csv(filename,encoding='euc-kr',thousands=',')
j

# 행정구역의 법정동코드와 시군구를 분리.index기준 가로 추가
j=j.join(
    j['행정구역'].str.split('(',expand=True)
)
j[1]=j[1].str.replace(')','')
j.head(1)

# 칼럼명 수정하기
j.rename({0:'시군구',1:'법정동코드'},axis=1,inplace=True)
# 독산동 인구 현황
# endswith
# startswith
독산=j[j['시군구'].str.contains('독산')]
독산=독산.drop('2021년12월_계_총인구수',axis=1)
독산=독산.drop('2021년12월_계_연령구간인구수',axis=1)

독산

독산제1동=j[j['시군구'].str.endswith('독산제1동')]
독산제1동=독산제1동.drop(['2021년12월_계_총인구수','2021년12월_계_연령구간인구수'],axis=1)
ad=독산제1동.drop(['행정구역','시군구','법정동코드'],axis=1)
# 추출
aad=독산제1동.loc[:,'2021년12월_계_0세':'2021년12월_계_100세 이상']
aad.T.plot()

ad.info()

# 분산 그래프
import seaborn as sns
from scipy.stats import norm
# sns.FacetGrid(j, row = '행정구역').map(sns.distplot, 독산제1동.values)

sns.distplot(ad.values, fit=norm, kde=False)

