# -*- coding: utf-8 -*-
"""전국 신규 분양 민간 아파트 동향 분석

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DaGF60xeBcAwhP2WhAH6b65PyPXZtSmY

#한글적용
"""

# 코랩 한글 적용
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf
# 코랩 한글 적용 후 런타임 재시작
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')
plt.rc('axes', unicode_minus=False)

"""#데이터 불러오기"""

!cp *.csv /content/drive/MyDrive

import pandas as pd
filename='/content/drive/MyDrive/min2111.csv'
apr=pd.read_csv(filename,encoding='euc-kr',thousands=',')
apr.info()

"""#소스코드"""

apr['분양가격(제곱미터)'].unique()

apr.isna().sum()

apr=apr.fillna(0)
apr

apr.isna().sum()

apr=apr.fillna('0')
apr['분양가격(제곱미터)']=apr['분양가격(제곱미터)'].str.replace(',','').str.replace(' ','').str.strip()
apr[apr['분양가격(제곱미터)']=='']='0'
apr[apr['분양가격(제곱미터)']=='NaN']='0'

apr['분양가격(제곱미터)']=apr['분양가격(제곱미터)'].astype(int)

apr.info()

apr[apr['분양가격(제곱미터)']=='NaN']=0

apr['분양가격(제곱미터)']

# 지역별 평균 분양가 출력, 시각화
b=apr.pivot_table(
    index='지역명',
    values='분양가격(제곱미터)'
)
b=b.drop('0')

b.plot()

# 연도별 평균 분양가 출력 시각화
c=apr.pivot_table(
    index='연도',
    values='분양가격(제곱미터)'
)
c=c.drop('0')
c

c.plot()

# 지역별 연도별 평균 분양가 시각화는 heatmap
d=apr.pivot_table(
    index='연도',
    columns='지역명',
    values='분양가격(제곱미터)'
)
d=d.drop('0')
d=d.drop('0',axis=1)

import numpy as np
heat_table=d.corr()
mask = np.zeros_like(heat_table)
mask[np.triu_indices_from(mask)] = True

import seaborn as sns
plt.figure(figsize=(10,10))
sns.heatmap(
    heat_table,
    mask = mask,
    cmap='coolwarm',
    annot = True,
    fmt='.2f'
)

import seaborn as sns
plt.figure(figsize=(10,10))
sns.heatmap(
    d,
    annot = True,
    fmt='.2f'
)

