# -*- coding: utf-8 -*-
"""2. 환율 금값.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D6h2CMuTdewzMsd45hsKP65zXSk8bb1x

### import
"""

import pandas_datareader as pdr
import seaborn as sns
import numpy as np
import pandas_datareader.data as web
from pandas_datareader import wb
import requests
import pandas as pd
import datetime
import FinanceDataReader as fdr

"""# 환율"""

ALPHAVANTAGE_API_KEY="G4F53WGNXCNW21AF"
ex_rate = web.DataReader("USD/KRW", "av-forex", api_key=ALPHAVANTAGE_API_KEY)
ex_rate.head()

"""#### 월별"""

url = 'https://www.alphavantage.co/query?function=FX_MONTHLY&from_symbol=USD&to_symbol=KRW&apikey='+ALPHAVANTAGE_API_KEY
r = requests.get(url)
data = r.json()
ex_rate2=pd.DataFrame(data['Time Series FX (Monthly)']).T
ex_rate2.head()

ex_rate2=ex_rate2.rename(columns={'4. close': 'close'})

ex_rate2.index=pd.to_datetime(ex_rate2.index) #시계열지정

ex_rate2.close=pd.to_numeric(ex_rate2.close)

ex_rate2.close.round()

ex_rate2.close.astype(int)

ex_rate2.index.name='date'

sns.lineplot(x=ex_rate2.index,y=ex_rate2['close'])

"""#### 일별"""

url = 'https://www.alphavantage.co/query?function=FX_DAILY&from_symbol=USD&to_symbol=KRW&apikey='+ALPHAVANTAGE_API_KEY
r = requests.get(url)
data = r.json()
ex_rate3=pd.DataFrame(data['Time Series FX (Daily)']).T
ex_rate3.head()

ex_rate3=ex_rate3.rename(columns={'4. close': 'close'})

ex_rate3.index=pd.to_datetime(ex_rate3.index) #시계열지정

ex_rate3.close=pd.to_numeric(ex_rate3.close)

ex_rate3.close.round()

ex_rate3.close.astype(int)

ex_rate3.index.name='date'

sns.lineplot(x=ex_rate3.index,y=ex_rate3['close'])

"""# 금값"""

start=datetime.datetime(2020,1,1)
end=datetime.datetime(2021,7,15)

gold=web.DataReader('GOLDAMGBD228NLBM','fred',start,end)
gold.head()

gold=gold.rename(columns={'GOLDAMGBD228NLBM':'price'})

gold.index=gold.index.rename('date')

gold.price=pd.to_numeric(gold.price)

gold=gold[['price']].dropna()

gold=gold[['price']].round()

gold=gold[['price']].astype(int)

sns.lineplot(x=gold.index,y=gold['price'])